# Generated by Django 5.1.4 on 2024-12-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('WALKIN', 'Walk-in')], max_length=20)),
                ('transaction_type', models.CharField(choices=[('MEDICAL', 'Medical Consultation'), ('DENTAL', 'Dental Consultation'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('queue_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
