# Generated by Django 5.1.4 on 2024-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='certificate_type',
            field=models.CharField(blank=True, choices=[('ABSENCE', 'Absence'), ('EMPLOYMENT', 'Employment'), ('OJT', 'OJT'), ('OSRA', 'OSRA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('PERSONNEL', 'Personnel'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='special_tag',
            field=models.CharField(choices=[('PWD', 'Person with Disability'), ('SENIOR_CITIZEN', 'Senior Citizen'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
