# Generated by Django 5.1.4 on 2024-12-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_ticket_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
