# Generated by Django 5.1.4 on 2024-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_ticket_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_group',
            field=models.CharField(choices=[('NURSE', 'Nurse'), ('DENTIST', 'Dentist'), ('PHYSICIAN', 'Physician')], default='NURSE', max_length=20),
        ),
    ]
