# Generated by Django 5.1.4 on 2024-12-14 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_ticket_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='queue_number',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
