# Generated by Django 5.1.4 on 2024-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_alter_ticket_queue_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='queue_number',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
