# Generated by Django 5.1.3 on 2025-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0009_ticket_checked_in_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
