# Generated by Django 5.1.3 on 2025-01-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0010_ticket_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='label',
            field=models.CharField(blank=True, default='In Queue', max_length=20, null=True),
        ),
    ]
