# Generated by Django 5.1.3 on 2024-12-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
